@startuml DataHandler
skinparam groupInheritance 2
hide <<category>> circle
hide <<kind>> circle
hide <<phase>> circle
hide <<role>> circle
hide <<collective>> circle
hide members
hide methods

class ProjectObservatory<<kind>> #4A90E2 {}
class ProcessManager <<role>> #7ED321 {}
class DataHandler <<role>> #7ED321 {}
ProjectObservatory <|-- ProcessManager
ProcessManager <|-- DataHandler

class Extractor <<phase>> #F5A623 {}
class Treator <<phase>> #F5A623 {}
class Loader <<phase>> #F5A623 {}
DataHandler <|-- Extractor
DataHandler <|-- Treator
DataHandler <|-- Loader

class Data <<category>> #d72d27 {}
Data <|-- ProjectData

class ProjectData <<kind>> #4A90E2 {}
class RawData <<phase>> #F5A623 {}
class DataArtifact <<collective>> #BD93BD {}
class ProcessedData <<phase>> #F5A623 {}
class DataStore <<collective>> #BD93BD {}  
ProjectData <|-left- RawData
DataArtifact "1" *-up- "1..*" RawData : <<MemberOf>>
ProjectData <|-right- ProcessedData
DataStore "1" *-up- "1..*" ProcessedData : <<MemberOf>>
Extractor "1" -- "1..*" RawData : extracts >
Treator "1" -- "1..*" RawData : treats >
Loader "1" -- "1..*" ProcessedData : loads >

class KnowledgeProducer <<role>> #7ED321 {}
ProcessManager <|-- KnowledgeProducer

class InformationProducer <<role>> #7ED321 {}
class Classifier <<phase>> #F5A623 {}
class Combiner <<phase>> #F5A623 {}
class Transformer <<phase>> #F5A623 {}
class Information <<kind>> #4A90E2 {}
class Logger <<phase>> #F5A623 {}
KnowledgeProducer <|-- InformationProducer
InformationProducer <|-- Classifier
Classifier "1" -- "1..*" ProcessedData : classifies >
InformationProducer <|-- Combiner
Combiner "1" -- "1..*" ProcessedData : combines >
InformationProducer <|-- Transformer
Transformer "1" -- "1..*" ProcessedData : transforms >
Transformer "1" -- "1..*" Information : produces >
InformationProducer <|-- Logger
Logger "1" -- "1..*" Information : logs >

class InformationSupplier <<role>> #7ED321 {}
KnowledgeProducer <|-- InformationSupplier
InformationSupplier "1" -- "1..*" Information : supplies >

class InformationConsumer <<role>> #7ED321 {}
KnowledgeProducer <|-- InformationConsumer
InformationConsumer "1" -- "1..*" Information : consumes >

class InformationEvaluator <<role>> #7ED321 {}
KnowledgeProducer <|-- InformationEvaluator
InformationEvaluator "1" -- "1..*" Information : evaluates >

class Knowledge <<kind>> #4A90E2 {}
KnowledgeProducer "1" -- "1..*" Knowledge : enables >

@enduml
