@startuml MPO Agents Formalization
hide members
skinparam style strictuml

class Agent <<Kind>> #A8D08D {}
class ObservatoryUser <<Role>> #FFE699 {}
class StakeHolder <<Role>> #FFE699 {}
class System <<Role>> #FFE699 {}
class ObservatoryGroup <<Collective>> #9BC2E6 {}

ObservatoryUser -down-|> Agent
StakeHolder -down-|> Agent
System -down-|> Agent
ObservatoryGroup "1" -down-* "0..*" ObservatoryUser: <<MemberOf>>
ObservatoryGroup "1" -down-* "0..*" StakeHolder: <<MemberOf>>
ObservatoryGroup "1" -down- "0..*" System: <<MemberOf>>

@enduml
