@startuml MPO Structures Observatory Formalization
hide members
skinparam style strictuml

class ProjectObservatory <<SubKind>> #C6E0B4 {}

class View <<Role>> #FFE699 {}
class Relator <<Role>> #FFE699 {}
class Disseminator <<Role>> #FFE699 {}
class DataManager <<Role>> #FFE699 {}
class Collector <<Role>> #FFE699 {}
class Processor <<Role>> #FFE699 {}
class Storer <<Role>> #FFE699 {}
class Project <<Kind>> #A8D08D {}
class Management <<relator>> #F4B084 {}

ProjectObservatory <|-- DataManager
ProjectObservatory <|-- View
View "1" -left- "0..*" Management : <<mediation>>
Relator -up-|> View
Disseminator -up-|> View
DataManager "1" - "0..*" Management : <<mediation>>
Collector -up-|> DataManager
Processor -up-|> DataManager
Storer -up-|> DataManager
Project "1" -up- "0..*" Management : <<mediation>>

@enduml
