@startuml MPO Structures Observatory Infra Formalization
hide members
skinparam style strictuml

class Software <<Kind>> #A8D08D {}
class Hardware <<Kind>> #A8D08D {}
class Network <<Kind>> #A8D08D {}
class Connection <<relator>> #F4B084 {}
class Service <<Kind>> #A8D08D {}
class Operation <<relator>> #F4B084 {}

Software "1..*" *-down- "1..*" Hardware: <<CompOf>>
Hardware "1" -down- "0..*" Connection : <<med>>
Network "1" -left- "0..*" Connection : <<med>>
Operation "0..*" -left- "0..*" Software : <<med>>
Operation "0..*" -left- "0..*" Hardware : <<med>>
Operation "0..*" -down- "0..*" Network : <<med>>
Service "1" -down- "0..*" Operation : <<med>>

@enduml
