@startuml MPO Structures Classification Tree

package "IT Infrastructure" as Infra {
    class Service {
        + type: str
        + subtype: str
        - provider: str
        - local: str
        - start_period: datetime
        - end_period: datetime
        - cost: float
        - availability: float
    }
    class Hardware {
        + type: str
        + specification: str
        + purpose: str
        - local: str
        - compute_capacity: str
        - storage_capacity: str
    }
    class Network {
        + type: str
        + topology: str
        + scope: str
        + protocol: str
        - local: str
        - state: str
        - bandwidth: str
        - security: str
    }
    class DataManagement {
        + type: str
        + deploy_model: str
        + format: str
        + purpose: str
        - name: str
        - version: str
    }
    class Software {
        + deploy_model: str
        + environment: str
        + license: str
        + purpose: str
        - name: str
        - version: str
    }

    Software --> DataManagement : uses
    Software --> Hardware : runs on
    DataManagement -left-> Hardware : runs on
    Hardware --> Network : connects through
}

package "Content" as Content {
    class Observatory {
        + theme: str
        + purpose: str
        + scope: str
        - name: str
        - owner: str
    }

    class UserLog {
        + purpose: str
        - action: str
    }

    class Project {
        + type: str
        + theme: str
        + objective: str
        + scope: str
        - started_at: datetime
        - ended_at: datetime
        - name: str
        - status: str
        - description: str
        - budget: float
    }

    Observatory -down-> Project: has
    Observatory -down-> UserLog: includes
}

package "SoftwareComponents" as SoftComp {
    class Disseminator {
        + target: str
        + purpose: str
        - channel: str
        - frequency: str
        - tool: str
        - format: str
        - reach: str
    }

    class Relator {
        + type: str
        + purpose: str
        - channel: str
        - frequency: str
    }
}

package "DataManagementComponents" as DataComp {
    class Collector {
        + method: str
        + source: str
        + frequency: str
        - tool: str
        - size: str
        - quality: str
    }

    Class Processor {
        + method: str
        + scope: str
        + automation_level: str
        + purpose: str
        - tool: str
        - size: str
        - performance: str
        - result: str
    }

    class Storer {
        + type: str
        + model: str
        + durability: str
        + purpose: str
        - local: str
        - capacity: str
    }
}

Service -up-> Infra : operates and maintains
Software -down-> SoftComp : includes
DataManagement -down-> DataComp : includes
Observatory -left-> Infra : depends on

@enduml
