@startuml DataHandler
skinparam groupInheritance 2
hide <<kind>> circle
hide <<phase>> circle
hide <<role>> circle
hide <<collective>> circle
hide members
hide methods

class ProjectObservatory<<kind>> #4A90E2 {}
class ProcessManager <<role>> #7ED321 {}
class DataHandler <<role>> #7ED321 {}
class KnowledgeProducer <<role>> #7ED321 {}

ProjectObservatory <|-- ProcessManager
ProcessManager <|-- DataHandler
ProcessManager <|-- KnowledgeProducer

class Extractor <<phase>> #F5A623 {}
class Transformer <<phase>> #F5A623 {}
class Loader <<phase>> #F5A623 {}

DataHandler <|-- Extractor
DataHandler <|-- Transformer
DataHandler <|-- Loader

class Data <<kind>> #4A90E2 {}
class RawData <<phase>> #F5A623 {}
class ProcessedData <<phase>> #F5A623 {}

Data <|-left- RawData
Data <|-right- ProcessedData

class DataSource <<collective>> #BD93BD {}
class DataStore <<collective>> #BD93BD {}

DataSource "1" *-- "1..*" RawData : <<MemberOf>>
DataStore "1" *-- "1..*" ProcessedData : <<MemberOf>>

class DataEntryArtifact<<phase>> #F5A623 {}
class BufferedDataArtifact<<phase>> #F5A623 {}
class ProcessedDataArtifact<<phase>> #F5A623 {}

DataSource <|-up- DataEntryArtifact
DataSource <|-up- BufferedDataArtifact
DataSource <|-up- ProcessedDataArtifact

Extractor "1" -- "1..*" DataEntryArtifact : extracts >
Transformer "1" -- "1..*" BufferedDataArtifact : transforms >
Loader "1" -- "1..*" ProcessedDataArtifact : loads >
ProcessedDataArtifact "1..*" -- "1" DataStore : stored in >

@enduml
